package com.dems;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class GenerateReportServlet extends HttpServlet {
    
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");

        String reportType = request.getParameter("report_type");
        String filePath = request.getParameter("file_path");
        String generatedBy = request.getParameter("generated_by"); 
        if (reportType == null || filePath == null || generatedBy == null) {
            response.sendRedirect("investigator-dashboard.jsp?error=Missing required fields");
            return; 
        }

        int generatedById = 0;
        try {
            generatedById = Integer.parseInt(generatedBy);  
        } catch (NumberFormatException e) {
            response.sendRedirect("investigator-dashboard.jsp?error=Invalid Generated By value");
            return;
        }

        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dems", "root", "Payal@2005");

            String sql = "INSERT INTO roport (generated_by, report_type, file_path, generated_at) VALUES (?, ?, ?, now())";
            pstmt = conn.prepareStatement(sql);

            pstmt.setInt(1, generatedById);
            pstmt.setString(2, reportType); 
            pstmt.setString(3, filePath); 
            Timestamp timestamp = new Timestamp(new Date().getTime());
            pstmt.setTimestamp(4, timestamp);
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                response.sendRedirect("investigator-dashboard.jsp?message=Report Generated Successfully");
            } else {
                response.sendRedirect("investigator-dashboard.jsp?error=Error generating report");
            }
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            response.sendRedirect("investigator-dashboard.jsp?error=Error generating report");
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
