<%@ page import="java.sql.*, java.util.*" %>
<%@ page import="javax.sql.DataSource" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Prosecutor Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>

<h2>Evidence List</h2>
<table>
    <tr>
        <th>Evidence ID</th>
        <th>Case ID</th>
        <th>Type</th>
        <th>Uploaded By</th>
        <th>File Name</th>
        <th>Collected At</th>
    </tr>
    <%
        List<Map<String, String>> evidenceList = (List<Map<String, String>>) request.getAttribute("evidenceList");
        if (evidenceList != null) {
            for (Map<String, String> evidence : evidenceList) {
    %>
    <tr>
        <td><%= evidence.get("evidence_id") %></td>
        <td><%= evidence.get("case_id") %></td>
        <td><%= evidence.get("evidence_type") %></td>
        <td><%= evidence.get("uploaded_by") %></td>
        <td><%= evidence.get("file_name") %></td>
        <td><%= evidence.get("collected_at") %></td>
    </tr>
    <%
            }
        }
    %>
</table>

<h2>Generated Reports</h2>
<table>
    <tr>
        <th>Report ID</th>
        <th>Generated By</th>
        <th>Type</th>
        <th>File Path</th>
        <th>Generated At</th>
    </tr>
    <%
        List<Map<String, String>> reportList = (List<Map<String, String>>) request.getAttribute("reportList");
        if (reportList != null) {
            for (Map<String, String> report : reportList) {
    %>
    <tr>
        <td><%= report.get("report_id") %></td>
        <td><%= report.get("generated_by") %></td>
        <td><%= report.get("report_type") %></td>
        <td><%= report.get("file_path") %></td>
        <td><%= report.get("generated_at") %></td>
    </tr>
    <%
            }
        }
    %>
</table>

<h2>Access Logs</h2>
<table>
    <tr>
        <th>Log ID</th>
        <th>User ID</th>
        <th>Action Type</th>
        <th>Details</th>
        <th>Timestamp</th>
    </tr>
    <%
        List<Map<String, String>> logList = (List<Map<String, String>>) request.getAttribute("logList");
        if (logList != null) {
            for (Map<String, String> log : logList) {
    %>
    <tr>
        <td><%= log.get("log_id") %></td>
        <td><%= log.get("user_id") %></td>
        <td><%= log.get("action_type") %></td>
        <td><%= log.get("action_details") %></td>
        <td><%= log.get("timestamp") %></td>
    </tr>
    <%
            }
        }
    %>
</table>

</body>
</html>
